const AVALANCHE_MAINNET_CHAIN_ID = 43114n;
const AVALANCHE_NATIVE_SYMBOL = "AVAX";

const AXEN_MAINNET = "0xC0C5AA69Dbe4d6DDdfBc89c0957686ec60F24389";
const AXEN_EXPECTED_NAME = "XEN Crypto";
const AXEN_EXPECTED_SYMBOL = "aXEN";
const AXEN_EXPECTED_DECIMALS = 18;

const INITIAL_NOMINAL_TEXT = "100";
const INITIAL_XEN_BURN_TEXT = "100000000";

const DEPLOY_CONFIRMATION =
  "I_UNDERSTAND_THIS_DEPLOYS_XC_TO_AVALANCHE_MAINNET";
const GENESIS_CONFIRMATION =
  "FRESH_AVALANCHE_GENESIS_100_XNTD_100M_AXEN";
const INIT_CONFIRMATION =
  "BURN_DEPLOYER_RIGHTS_AND_FINALIZE_AVALANCHE_WIRING";

module.exports = {
  AVALANCHE_MAINNET_CHAIN_ID,
  AVALANCHE_NATIVE_SYMBOL,
  AXEN_MAINNET,
  AXEN_EXPECTED_NAME,
  AXEN_EXPECTED_SYMBOL,
  AXEN_EXPECTED_DECIMALS,
  INITIAL_NOMINAL_TEXT,
  INITIAL_XEN_BURN_TEXT,
  DEPLOY_CONFIRMATION,
  GENESIS_CONFIRMATION,
  INIT_CONFIRMATION,
};
